export const VERSION = "v2.3.103";

export const RELEASE_NOTES = {
  "2.3.103": "The compact weekly take-home summary now appears directly in the main Target view",
  "2.3.102": "Weekly dashboard adds economic net pay, accrued Uber operating costs, projections, and net hourly rate",
  "2.3.101": "Weekly earnings target now follows Settings and derives productive hours at £20 per hour",
  "2.3.100": "Weekly performance is simplified into colour-coded headline cards",
  "2.3.99": "Weekly progress adds productive-time tracking, planned-schedule pace, recovery guidance, and earnings-deficit attribution",
  "2.3.98": "Weekly tracking now uses one £1,000 earnings target with a matching 50-hour progress bar",
  "2.3.97": "Week summary treats insurance as a fixed weekly cost regardless of days worked",
  "2.3.96": "Weekly Target Ladder adds a working-limit check for sustainable recovery planning",
  "2.3.95": "Weekly Target Ladder adds floor, main, Mortgage Killer, serious hours, and end reasons",
  "2.3.94": "Live Shift Coach is archived and removed from the active Day screen",
  "2.3.93": "Live Shift Coach uses smaller media controls",
  "2.3.92": "Coach treats declined jobs with dead mileage or multiple stops as cautionary context",
  "2.3.91": "Live Shift Coach avoids timer re-renders and draft writes while dictating",
  "2.3.90": "Live Shift Coach prevents mobile dictation from triggering hidden chat submits",
  "2.3.89": "Live Shift Coach dictation uses a mobile-safe textarea and avoids touch-keyboard Enter submits",
  "2.3.88": "Live Shift Coach adds a clear chat control for the active shift",
  "2.3.87": "Coach classification now tracks safety, mental fatigue, reassurance need, and driver capacity",
  "2.3.86": "Coach framework now prioritises safety, wellbeing, intention, and one clear decision",
  "2.3.85": "Coach vocabulary gains validation tooling and maintenance guidance",
  "2.3.84": "Coach vocabulary now captures anonymised real driver phrases for future semantic examples",
  "2.3.83": "Coach extraction now loads structured phrase-library JSON examples for broader semantic understanding",
  "2.3.82": "Coach extraction understands wider driver language, slang, broken English, wellbeing, and conversation purpose",
  "2.3.81": "Live Shift Coach replies favour short conversational advice and one clear driver decision",
  "2.3.80": "Live Shift Coach opens chat history at the latest message after page reload",
  "2.3.79": "Live Shift Coach keeps chat pinned to the latest message when focusing the input",
  "2.3.78": "Live Shift Coach chat scrolls to the latest message after replies",
  "2.3.77": "Live Shift Coach chat sends reliably, clears after submit, and uses smaller app-aligned input styling",
  "2.3.76": "Live Shift Coach makes chat the primary panel and trims duplicate reply and controls",
  "2.3.75": "Live Shift Coach chat uses a single-line mobile-style composer",
  "2.3.74": "Live Shift Coach replaces the go-home card with a compact coach chat window",
  "2.3.73": "Live Shift Coach removes extra coach panels and uses compact media-style shift controls",
  "2.3.72": "Live Shift Coach focuses on coach chat, day progress, a go-home decision metric, and scrollable chat history",
  "2.3.71": "Day screen adds a collapsed Add Missed Session panel for retrospective entries",
  "2.3.70": "Day screen removes manual Log Session entry and opens Forecast Evidence by default",
  "2.3.69": "Live Shift focuses on checkpoints and saves the final session automatically when ending a shift",
  "2.3.68": "Coach infers emotion, market and intent from natural language instead of relying on phrase matching",
  "2.3.67": "Coach mirrors positive and negative emotional cues before reaching for metrics",
  "2.3.66": "Coach treats breaks, weak offers and split-shift intentions as energy mode before forecast maths",
  "2.3.65": "Coach only asks for trip data when a specific job review is clearly requested",
  "2.3.64": "Coach Chat is separated from checkpoints with larger auto-growing text for parked-driver use",
  "2.3.63": "Ask Coach voice is more conversational and avoids exact per-mile readouts in fallback replies",
  "2.3.62": "Ask Coach replies use a more conversational driver-coach tone",
  "2.3.61": "Ask Coach adds clear next-message handling after a coach reply",
  "2.3.60": "Ask Coach now uses AI extraction before app-calculated job metrics and coaching",
  "2.3.59": "Ask Coach understands pound-word fares and pickup distances phrased as miles away",
  "2.3.58": "Ask Coach reads natural pickup/drop-off wording and shows a thinking state",
  "2.3.57": "Ask Coach can call a secure backend OpenAI endpoint with local fallback coaching",
  "2.3.56": "Ask Coach now calculates logged job fare, pickup miles, trip miles, and full-distance value",
  "2.3.55": "Live Shift Coach adds an Ask Coach dialogue for driver questions",
  "2.3.54": "Live Shift Coach hides forecast evidence behind a reveal and adds driver notes",
  "2.3.53": "Live Shift Coach removes Energy Level entry and bases coaching on shift data only",
  "2.3.52": "Weekly Target now includes remaining target metrics on the same slide",
  "2.3.51": "Coach adds planned finish time, daily countdown guidance, and Month Summary projections",
  "2.3.50": "Day dashboard now has labelled Coach, Target, Remaining, and Week slide controls",
  "2.3.49": "Day flow now prioritises Coach and Weekly Target, with halfway target guidance focused on what remains",
  "2.3.48": "Driver Coach adds pause, trip workload, and message-first layout",
  "2.3.47": "Live Shift Coach tracks active shifts and quick checkpoints",
  "2.3.46": "Weekly statement entry is more compact and month picker has arrow navigation",
  "2.3.45": "Month Summary now uses one consistent gross figure for tax and hourly rate",
  "2.3.44": "Month tab now uses swipe slides with larger clickable controls",
  "2.3.43": "Work Efficiency cards now use softer numbers and colour accents",
  "2.3.42": "Month Summary now uses visual money-flow and efficiency charts",
  "2.3.41": "Uber import can read copied breakdown text from the clipboard and OCR retries more gracefully",
  "2.3.40": "iPhone screenshot import now reads the statement date area more aggressively",
  "2.3.39": "Uber statement import now supports choosing a screenshot from the photo library",
  "2.3.38": "Saving an Uber weekly statement now clears the import box",
  "2.3.37": "Uber weekly statements now warn before replacing a duplicate week",
  "2.3.36": "Screenshot import now OCR-reads the Uber breakdown area before falling back to the full screen",
  "2.3.35": "Uber breakdown import reads dates more reliably and avoids misplaced OCR amounts",
  "2.3.34": "Month tab can import Uber weekly breakdowns from pasted text or screenshots",
  "2.3.33": "Planning rate now stays anchored to Settings unless actuals are stronger",
  "2.3.32": "Weekly planning now derives required hours from the remaining revenue target",
  "2.3.31": "Weekly target strip keeps seven columns with wider usable spacing",
  "2.3.30": "Weekly target day values now use larger readable day cards",
  "2.3.29": "Target hours now respond to desired hourly rate and tab content stays contained",
  "2.3.28": "Day dashboard carousel now glides between slides",
  "2.3.27": "Day dashboard carousel now supports swipe navigation on mobile",
  "2.3.26": "Day dashboard now uses carousel slides with compact weekly target controls",
  "2.3.25": "Day sections reordered with today remaining separated from weekly progress",
  "2.3.24": "Target strip values now stay dark for better contrast",
  "2.3.23": "Previous week titles no longer truncate and session entry is more compact",
  "2.3.22": "Day view spacing tightened with stronger target borders and steadier week headings",
  "2.3.21": "Weekly targets can sync to Supabase and the Day view is more compact",
  "2.3.20": "Week navigation controls are now compact graphic buttons",
  "2.3.19": "Past week target outcomes are colour coded with separated date and status text",
  "2.3.18": "Current week is labelled Week to Date and past weeks show target-relative outcomes",
  "2.3.17": "Profitability summary now gives gross more emphasis and trims efficiency text",
  "2.3.16": "Weekly summary now shows a profitability bar with net hourly and cost metrics",
  "2.3.15": "Petrol fuel logging is restored and same-day miles are checked before saving",
  "2.3.14": "Friday and Saturday now carry higher weighted hours and cash targets",
  "2.3.13": "Hours remaining now subtracts hours already worked today before rebalancing future days",
  "2.3.12": "Day totals now calculate session earnings and miles, while weekly hours stay fixed and rebalance",
  "2.3.11": "Session gross now subtracts earlier same-day sessions and keeps time inputs side by side",
  "2.3.10": "Clock shorthand now rolls 60 minutes into the next hour and clamps future hour targets",
  "2.3.9": "Session logging now uses separate hours and minutes fields",
  "2.3.8": "Hours now display and accept clock shorthand where 7.5 means 7h 50m",
  "2.3.7": "Weekday targets now have a static fallback while the app script loads",
  "2.3.6": "Target controls simplified with aligned week buttons and cleaner week strips",
  "2.3.5": "Target amount and daily hours inputs now stay adjacent on narrow screens",
  "2.3.4": "Hours target layout refined with rebalanced hour strip and collapsible session history",
  "2.3.3": "Session hours and daily hours targets added to the Day workflow",
  "2.3.2": "Card section spacing restored across stacked dashboard panels",
  "2.3.1": "Missing charging table warning now stays inside the Charging tab",
  "2.3.0": "Charging summaries replace fuel logs for EV weekly and monthly operating costs",
  "2.2.27": "Mileage claim setting now uses a conservative flat 25p per mile",
  "2.2.26": "EV efficiency now uses Tesla-style miles per kWh",
  "2.2.25": "EV charging estimates now use off-peak p/kWh and vehicle efficiency settings",
  "2.2.24": "Behind-target progress wording softened to keep the dashboard operational",
  "2.2.23": "Primary target card now shows today's specific weighted target",
  "2.2.22": "Remaining week forecast tiles now rebalance from the current remaining target",
  "2.2.21": "Weekly target forecasts now use tighter mobile tiles, stored week snapshots, and Fri/Sat weighting",
  "2.2.20": "Weekly target default changes now refresh weeks that have not been manually overridden",
  "2.2.19": "Weekly target dynamic mode adds rolling four-week uplift targets and weekday forecasts",
  "2.2.18": "MTD mileage mode now excludes other expenses to avoid vehicle cost double counting",
  "2.2.17": "Mileage claim now tracks the 10,000 business mile threshold by tax year",
  "2.2.16": "Settings now controls MTD mileage claim versus actual vehicle costs",
  "2.2.15": "MTD_READY export now includes gross income and Uber fee breakdown",
  "2.2.14": "Google Sheets webhook updated to latest Apps Script deployment",
  "2.2.13": "MTD export errors now show Apps Script detail",
  "2.2.12": "MTD export payload now targets the MTD_READY sheet columns",
  "2.2.11": "Month summary restored to stacked section layout for readability",
  "2.2.10": "Month summary sections now render as responsive tiles",
  "2.2.9": "Month summary split into net income, tax summary, and performance sections",
  "2.2.8": "Uber weekly statement history and MTD rollup added to Month tab",
  "2.2.7": "Uber monthly statement entry and MTD export added to Month tab",
  "2.2.6": "Weekly target work days left now excludes days with saved sessions",
  "2.2.5": "Weekly target daily target now uses future planned work days only",
  "2.2.4": "Weekly target week controls and delete buttons for Costs history",
  "2.2.3": "Delete button added to worked session summary cards",
  "2.2.2": "iPhone live stylesheet cache fix and larger Costs toggle controls",
  "2.2.1": "Compact month dashboard, weekly day strip, Costs tab, EV settings, and iPhone-width layout",
  "2.2.0": "Settings tab added for targets, vehicle details, insurance, tax, and fuel assumptions",
  "2.1.5": "Weekly target wording simplified around required remaining daily target",
  "2.1.4": "Weekly target pace now follows required remaining daily target",
  "2.1.3": "Weekly target progress bar with red, amber, green pace states",
  "2.1.2": "Weekly target tracker, simplified day logging, compact finance cards, and blank end-time save fix",
  "2.1.1": "Weekly income target tracker added to Day workflow",
  "2.1.0": "Day & Month fuel calculations based on 3 most recent fills, station name removed from fuel form",
  "2.0.0": "Daily workflow replaces shifts. Added weekly day history, real-world retained view, and month summary based on days.",
  "1.5.1": "Trips add to shift workflow and Google Sheets",
  "1.4.2": "Changed shift model to use shift_miles",
  "1.4.1": "Confirm Google Sheets sync for shifts fuel and expenses.",
  "1.4.0": "Reconciliation pass. Single module bootstrap, fixed fuel history rendering, cleaned tab loading and date defaults.",
  "1.3.0": "Scripts changed to send multiple calls to Sheets for shift, fuel, expense.",
  "1.2.0": "History UI stabilisation. Compact shift, fuel and expense cards. Expense categories now load correctly.",
  "1.1.0": "Google Sheets shift sync and core shift save/load stabilisation."
};

export function getReleaseNotes(version = VERSION) {
  const cleanVersion = String(version).replace(/^v/i, "");
  return RELEASE_NOTES[cleanVersion] || "";
}





